// An object that knows all the ALLOWED ACTION TYPES

const ActionTypes = {

    CATEGORIES_ALL_REQ: 'CATEGORIES_ALL_REQ',
    CATEGORIES_ALL_OK:  'CATEGORIES_ALL_OK',
    CATEGORIES_ALL_X:   'CATEGORIES_ALL_X',

    CATEGORIES_FILTER_REQ:  'CATEGORIES_FILTER_REQ',
    CATEGORIES_FILTER_OK:   'CATEGORIES_FILTER_OK',
    CATEGORIES_FILTER_X:    'CATEGORIES_FILTER_X',

    CATEGORY_ADD_REQ:   'CATEGORY_ADD_REQ',
    CATEGORY_ADD_OK:    'CATEGORY_ADD_OK',
    CATEGORY_ADD_X:     'CATEGORY_ADD_X',

    CATEGORY_RND_REQ:   'CATEGORY_RND_REQ',
    CATEGORY_RND_OK:    'CATEGORY_RND_OK',
    CATEGORY_RND_X:     'CATEGORY_RND_X',

    CATEGORY_DEL_REQ:   'CATEGORY_DEL_REQ',
    CATEGORY_DEL_OK:    'CATEGORY_DEL_OK',
    CATEGORY_DEL_X:     'CATEGORY_DEL_X',
};

export default ActionTypes;
